
trigger: none  # Ensure it's not triggered automatically

parameters:
  - name: myParam
    type: string
    default: "defaultValue"

jobs:
  - job: TriggerMypipe
    steps:
      - script: |
          echo "Running mytrigger with parameter $(myParam)"

          # Triggering mypipe pipeline using the Azure DevOps REST API
          $uri = "$(System.CollectionUri)$(System.TeamProject)/_apis/pipelines/9999/runs?api-version=6.0-preview.1"

          $body = @{
              "resources" = @{
                  "pipeline" = @{
                      "id" = 9999  # Build Definition ID
                      "parameters" = @{
                          "myParam" = "$(myParam)"
                      }
                  }
              }
          } | ConvertTo-Json -Depth 10

          Write-Host "Triggering pipeline 9999 with body: $body"

          # Define the headers
          $headers = @{
              "Authorization" = "Bearer $(System.AccessToken)"
              "Content-Type" = "application/json"
          }

          # Trigger the pipeline via REST API
          Invoke-RestMethod -Uri $uri -Method Post -Headers $headers -Body $body
        env:
          SYSTEM_ACCESSTOKEN: $(System.AccessToken)











-------------;;




trigger: none  # Do not trigger automatically

parameters:
  environment: 'production'
  deploymentRegion: 'us-east'
  ns1: false
  ns2: false

stages:
  - stage: TriggerPowerPipeline
    displayName: "Trigger Power Pipeline Twice"
    jobs:
      - job: TriggerPowerJob
        steps:
          - ${{ if eq(parameters.ns1, true) }}:
              - script: echo "##vso[build.queue name=Power; parameters.environment=ns1; parameters.deploymentRegion=${{ parameters.deploymentRegion }}]"
                displayName: "Trigger Power Pipeline with ns1"

          - ${{ if eq(parameters.ns2, true) }}:
              - script: echo "##vso[build.queue name=Power; parameters.environment=ns2; parameters.deploymentRegion=${{ parameters.deploymentRegion }}]"
                displayName: "Trigger Power Pipeline with ns2"




------±++++++


trigger: none  # This pipeline should not trigger automatically

parameters:
  environment: 'production'
  deploymentRegion: 'us-east'
  ns1: false
  ns2: false

stages:
  - ${{ if eq(parameters.ns1, true) }}:
      - stage: TriggerPower1
        displayName: "Trigger Power1 Pipeline"
        jobs:
          - job: TriggerPower1Job
            steps:
              - script: echo "##vso[build.queue name=Power1; parameters.environment=${{ parameters.environment }}; parameters.deploymentRegion=${{ parameters.deploymentRegion }}]"

  - ${{ if eq(parameters.ns2, true) }}:
      - stage: TriggerPower2
        displayName: "Trigger Power2 Pipeline"
        jobs:
          - job: TriggerPower2Job
            steps:
              - script: echo "##vso[build.queue name=Power2; parameters.environment=${{ parameters.environment }}; parameters.deploymentRegion=${{ parameters.deploymentRegion }}]"









---------------------------------------

trigger: none  # This pipeline should not trigger automatically

resources:
  repositories:
    - repository: self  # This tells Azure DevOps to use the same repository

parameters:
  environment: 'production'
  deploymentRegion: 'us-east'

stages:
  - stage: TriggerPower1
    displayName: "Trigger Power1 Pipeline"
    jobs:
      - job: TriggerPower1Job
        steps:
          - script: echo "Triggering Power1 Pipeline"
          - script: |
              echo "##vso[build.queue name=power1.yaml;parameters.environment=${{ parameters.environment }};parameters.deploymentRegion=${{ parameters.deploymentRegion }}]"
  
  - stage: TriggerPower2
    displayName: "Trigger Power2 Pipeline"
    dependsOn: TriggerPower1  # Ensure Power2 runs only after Power1
    jobs:
      - job: TriggerPower2Job
        steps:
          - script: echo "Triggering Power2 Pipeline"
          - script: |
              echo "##vso[build.queue name=power2.yaml;parameters.environment=${{ parameters.environment }};parameters.deploymentRegion=${{ parameters.deploymentRegion }}]"







-----------------------------+

trigger: none  # The orchestrator does not trigger automatically

resources:
  pipelines:
    - pipeline: Power1Pipeline
      source: Power1
      trigger: none  # Ensure this pipeline doesn't trigger automatically

    - pipeline: Power2Pipeline
      source: Power2
      trigger: none  # Ensure this pipeline doesn't trigger automatically

parameters:
  environment: 'production'
  deploymentRegion: 'us-east'

stages:
  - stage: TriggerPower1
    displayName: "Trigger Power1 Pipeline"
    jobs:
      - job: TriggerPower1Job
        steps:
          - script: echo "Triggering Power1 Pipeline"
          - script: |
              echo "##vso[build.queue name=Power1;parameters.environment=${{ parameters.environment }};parameters.deploymentRegion=${{ parameters.deploymentRegion }}]"
  
  - stage: TriggerPower2
    displayName: "Trigger Power2 Pipeline"
    dependsOn: TriggerPower1
    jobs:
      - job: TriggerPower2Job
        steps:
          - script: echo "Triggering Power2 Pipeline"
          - script: |
              echo "##vso[build.queue name=Power2;parameters.environment=${{ parameters.environment }};parameters.deploymentRegion=${{ parameters.deploymentRegion }}]"